### ISSUE TITLE
Problem with dream picker tab width!

### ISSUE THREAD

**Issue by lolvip025** [DreamWall-Animation/dwpicker#107]
![image](https://github.com/user-attachments/assets/4f186db2-74c6-4933-9fdd-989b68f163fe)

I use Maya 2022.
I don't know if this is a dream picker bug, like right now only the dream picker tab has a problem with scaling down in width, like the width is locked, I wonder if anyone else has the same problem or knows how to fix it.

**Comment by luckylyk** [comment]
Hi Lolvip,
This is due to the fact your scene contains and extreeeeeeeeeemly long namespace somewher ^^
The drop down menu adapt automatically his size.
You can disable this behavior unchecking this preferences: Edit >> Preferences >> Autoresize namespace combo

![image](https://github.com/user-attachments/assets/b9a9f791-5a0b-45b9-a9b4-bb093f437f53)


have a nice day
Lio
