### ISSUE TITLE
(nested ?) Namespace error

### ISSUE THREAD

**Issue by SupZeta** [DreamWall-Animation/dwpicker#15]
Hi!

Im having problems with the namespace. Want to check if its from the picker side.

When referencing a rig which changes the original rig namespace. 
Original rig namespace:  rig_group_name
Referenced rig namespace: file_name:rig_group_name

When doing this (referencing the rig), my IK/FK switch code stops working, because it doesn't find the namespace "rig_group_name" because now it has been changed to "file_name:rig_group_name"

Is this something the picker can control? 

Cheers.

**Comment by luckylyk** [comment]
You mean selection is not working anymore or you command button with the name hardcoded inside ?
1. I think maya have an option at referencing time to not create a new namespace. I don't remind exactly how it does behave.
![image](https://user-images.githubusercontent.com/25019043/151597178-3c174eda-7d3f-41d0-bb5d-929b7472340a.png)

2. If it is inside your code, I can't really do anything. You should adapt it, to make it able to detect automatically your namespace. We could implement a kind of variable in the command string which is replacing some value. But i'm not sure that add a layer over python and mel is a good idea.

3. If it is the selection not working with nested namespaces (which is not tested i think), let me take a look, i will fix that.

**Comment by SupZeta** [comment]
Thanks for the quick answer.

Selection is working correctly. But when turning off "use namespace" at reference options, selection stops working. The picker cant find a namespace to use.

I guess its as you say, I have to make the code to auto detect the namespace.

Thanks for your time!!
Cheers.

**Comment by luckylyk** [comment]
`Selection is working correctly. But when turning off "use namespace" at reference options, selection stops working. The picker cant find a namespace to use.`
What do you mean ? doing that you dont have any namespace at all ?
In that case you can set the *root*. May by the dialogbox it is not possible (i will check and add it if necessay). Otherwize, if you display the "namespace toolbar" in the preferences, you can set the root as the namespace to use.

**Comment by SupZeta** [comment]
> What do you mean ? doing that you dont have any namespace at all ?

The scene has a namespace but the picker doesn't find it. Even setting "root" as current namespace at "namespace editor"

**Comment by luckylyk** [comment]
could you send me the scene ?
That i can take a look on that. I'm curious. It look like a bug or an unsupported (yet) situation.

**Comment by luckylyk** [comment]
of course brouyere@dreamwall.be

**Comment by SupZeta** [comment]
Hi Lionel.

Wanted to ask you if there is a way to fetch the namespace from the picker by code?

We have tried with this but it doesn't work.

`import dwpicker
ns = dwpicker._dwpicker.namespace_combo.currentText()` 

Cheers.

**Comment by luckylyk** [comment]
Hey :)
I'm surprised that your snippet is not working, it is on my side. But it is a little bit hacky.
I just push a more "official" to do that: https://github.com/DreamWall-Animation/dwpicker/blob/main/scripts/detect_current_namespace.py
Still have to look about your scene. Sorry for the delay

**Comment by SupZeta** [comment]
Thanks!
No worries, I can use shelve buttons in the mean while, no big deal!

**Comment by luckylyk** [comment]
Ok, I took a look to your scene and I got what happened.

It seems that when we create a reference unchecking the "Use namespaces" option, Maya uses  prefix instead of namespace. This creates that kind of node names **"<filename>_<node>"**.
Of course the picker is broken because every node has been renamed.
Actually, the most dumb stuff is, if you want to create a reference in the root namespace, you need to check "Use namespaces", combined with the third option:
![image](https://user-images.githubusercontent.com/25019043/151865629-da9ef9be-a732-4273-9dd0-e4c98ce2342a.png)
And the, you get the good result:
![image](https://user-images.githubusercontent.com/25019043/151866283-3d5b302f-8dd1-425f-a6b4-44c47657e0fd.png)
The default behavior (first option) giving this namestyle **"<filename>:<node>"** works fine as well.

To make it short, never uncheck that f******g checkbox :D.
Sorry again for the delay (but it was week end at least ;))
As it seems that everything works fine, I will close the Issue and remove the rig file from my mail and machine :) !

Good luck
Lio
