### ISSUE TITLE
can't use add background item

### ISSUE THREAD

**Issue by ann40** [DreamWall-Animation/dwpicker#16]
Hi, I just download the 2022 version, I am using it on maya 2017, and when I start creating a picker, I find that I was not able to 
use the " add background item", I saved my image in both jpg and png, but the button was not able to detect those images. it only detects msi and mp4, I am not sure why.

**Comment by luckylyk** [comment]
what do you mean by: "not able to detect those images" ? You mean it is not appearing in the file dialog box ? Or you can select but it is not rendered ?
![image](https://user-images.githubusercontent.com/25019043/152040305-2b0e8749-92f2-4c6c-8001-8885f3b04b3f.png)
I assume it is the second one as the dialog box doesn't filter any file type.

So the picker is tested from Maya 2018 -> 2022. If I remember well, Maya 17 is using an alpha binding of PySide2. May png wasn't supported well at that time. But I will not guess on it because png is a really common feature and I have no memories of that kind of bugs.

The other possibility is a "path" bad reformating issue. On which os are you working ? 
Could you check the path of the background add ? To check:
    - Open the advanced editor (Edit -> Advanced Editor)
    - Uncheck: lock background selection icon in the toolbar:
![image](https://user-images.githubusercontent.com/25019043/152041136-d5948073-671e-4fcf-a4b1-d3f55922bdff.png)
    - Select the background item (which is probably transparent in your case)
    - In the Image panel, check the path
![image](https://user-images.githubusercontent.com/25019043/152041437-09e972a5-31e3-4292-b7fb-f8ca2ec777c4.png)

May you have a wrong slash in the wrong way depend on your OS. Or the filename is a relative like '../../images/file.png' which is not supported.

Keep me up.

**Comment by ann40** [comment]
Thanks for the quick response Lionel, it's actually the first case, so I add background image through here:[cid:07576bf5-4bdb-497a-9899-02aea5679b85]
[cid:101b93ec-0663-4349-a312-960e5bda9f20]

but I can not see the png file in this folder which I saved, I saved a png and a jpg image here.

[cid:8cdcfe9a-f0ce-40f5-be19-9d71f5ca873d]
________________________________

**Comment by ann40** [comment]
[cid:2b0b5edc-0196-4844-91a1-747d5eece263] I also tried to go by here as well, but it's the same, the png and the jpg in the folder was not showing

________________________________

**Comment by ann40** [comment]
btw I did uncheck the lock to try to do it.

[cid:f17178d2-6c45-4437-a087-d136022d6e28]

________________________________

**Comment by luckylyk** [comment]
Sorry but it seems that your capture are not working to me, I can't see them. So i'm not sure to really understand :)
 -What OS are you using ?

You can try this:
 -Click this icon in the advanded editor.
![image](https://user-images.githubusercontent.com/25019043/152052755-47c421f0-54bd-4a03-a681-01cde4a06a6e.png)
 -Uncheck the lock and select the shape created.
 -Paste the absolute path of your image in the field _Image -> Path_ without using the filedialog.
 -Set _Image -> Fit to shape_ as _true_.
That what happen under the hood when you add background. Tell me if that helps.

**Comment by ann40** [comment]
I am sorry I found the reason why this is happening, it was my problem, your script doesn't have any problem, sorry
about that, and thanks for answering me! it's good now!

________________________________

**Comment by luckylyk** [comment]
👍

**Comment by Karamjeet2794** [comment]
can you tell me how did you fix that

**Comment by luckylyk** [comment]
Reading his message it seems that finally: there was no issue to fix.
Btw, the tool massively changed since 2022. 
I invite you to open a new ticket to describe your specific problem (if you need help of course). I'll be glad to help.

**Comment by sleepyanimator** [comment]
Hello, I also have a similar problem. I am trying to upload a photo, however it's not registering.

**Comment by luckylyk** [comment]
> Hello, I also have a similar problem. I am trying to upload a photo, however it's not registering.



> can you tell me how did you fix that

As said above, this is a very old ticket, with issue coming from very old version.
Could you please create a new one describing in detail the wrong picker behavior ?
