### ISSUE TITLE
advanced editing not functioning for maya 2022 mac

### ISSUE THREAD

**Issue by felinlol** [DreamWall-Animation/dwpicker#19]
The advanced editing window will appear and close really quickly the first time after restarting Maya. If I try to open it again, the window doesn't appear at all. Could you look into this? Thank you.

**Comment by luckylyk** [comment]
Hi, do you have some precisions about this ? Any feedback in the Maya's script editor ? Like this i'm a bit clueless.

**Comment by felinlol** [comment]
Hi. The script editor shows the following error when I import dwpicker.  
```
import dwpicker
dwpicker.show()

# Traceback (most recent call last):
#   File "/Users/myname/Library/Preferences/Autodesk/maya/2022/prefs/scripts/dwpicker/main.py", line 481, in call_edit
#     if self.editors[index] is None:
# IndexError: list index out of range
```

I can still use the picker, just not the advanced editing window. No new output when I try to open the advanced editing window. Sorry I couldn't be more helpful.

**Comment by luckylyk** [comment]
Thanks for this,
This is seems odd because, launching the picker is not supposed to trigger this item. But your error message is limited to last call. Could you provide a more detailed trace ? You have to activate the "Show stack trace" item in the Script editor:
![image](https://user-images.githubusercontent.com/25019043/153828313-487e9d4f-e44b-43aa-ab5e-d4d55e934210.png)

By the way I added a warning when trying to open the advanced editor without having any picker tab opened.
Can you try and tell me if this is fixing the situation ?

**Comment by luckylyk** [comment]
@felinlol 
Any news on this ?

**Comment by felinlol** [comment]
Problem solved. It's working now. Thank you!
