### ISSUE TITLE
Environment paths for images

### ISSUE THREAD

**Issue by Alehaaaa** [DreamWall-Animation/dwpicker#42]
I work constantly switching PC and, due to that, changing image paths every time I open Maya.
Is there any way you could implement ENV PATHS for the images? Would be really helpful.

If not, as AnimSchool does, can you keep the image as base64 in the maya scene?

**Comment by luckylyk** [comment]
Hi,
Include images in the maya is not an option to me. Especially because the tool can hold an unlimited number of images (compared to AnimSchool which is limited to one background).

By the way, ENV PATHS are already supported :)
you can use any kind of env paths as far as it is supported by python 'os' module (os.path.expandvars() function)
e.g. "$PROJECT_ROOT/assets/character/smurf/pickerbg.png".

I close the ticket.
If you need precision, do not hesitate to reopen it.
Lio
