### ISSUE TITLE
bug "Add background item"

### ISSUE THREAD

**Issue by faxwang** [DreamWall-Animation/dwpicker#53]
Hello,
new background add in picker,will be in bottom of old background
v 0.6.0

**Comment by luckylyk** [comment]
Hi, this is not a bug, this is the expected behavior.

It add a background image. 
This item is a legacy to help transition from AnimSchool. It is not really consistant with our tool. 
The reason is that AnimSchool is only supporting one image per picker. As the number of images with DWPicker is unlimited I have no way to know which shape is the background to replace. Then you have to remove it manually from the advanced editor.

At some point this item will be removed.
