### ISSUE TITLE
AUTO Refresh UI selection, option to turn it OFF and auto-Focus UI.

### ISSUE THREAD

**Issue by alfsici** [DreamWall-Animation/dwpicker#6]
Is it possible to add an option on the main UI, to turn off "AUTO update" for the selection?
This seems to bite quite a few resources while keeping the UI Open and selecting stuff inside the maya viewport.
Ideally, an option to have this functionality On or OFF, would be perfect, since is a very useful option to keep it on, but
also to be able to turn off (for instance if the ui has only scripts buttns and not selections pickers)

Another thing that i noticed, is that the Picker Ui, seems to gain focus when the mouse rolls over it (without clicking) and looses focus when moving off .
Focus should stay with maya UI priority, since few animation scripts might cause a few headaches while working with the UI open .(Eg, graph editor is open with curve selected, the mouse goes over the Picker, the picker focuses, then the mouse moves into maya viewport, the focus has changed again without the user clicking, the auto stealing focus is a bit annoying to work with, and the picker keeps popping up over other windows, by accidental mouse, passing on it)

**Comment by luckylyk** [comment]
Currently it is possible to turn off the 'Auto update' selection programatically using a decorator. This is usefull because we encountered issues with some custom script updating selection in a loop.
You can use it like this.
`import dwpicker
with dwpicker.disable():
    """do your stuffs"""`
By the way, I will add the option to manually turn it off. Don't think it is too expensive to add.

Auto focus is a feature requested by my animators. If you turn it of, you have to set the focus on the window first you click a button. And they wanted to be able to press F without clicking the maya view port as well. You can partially disable it unchecking the 'auto-focus' item. 
Anyway, I will take a look to make it more configurable.

**Comment by alfsici** [comment]
Thank you for this.

**Comment by luckylyk** [comment]
![image](https://user-images.githubusercontent.com/25019043/150187418-4b21d8e1-e129-4b7a-a25b-8d7d853bc792.png)
This should resolve this ticket ;)
