### ISSUE TITLE
Can't delete old pickers

### ISSUE THREAD

**Issue by Kersey3d** [DreamWall-Animation/dwpicker#79]
Hello,

I've got an issue where I can't seem to delete older pickers.
The picker had randomly started opening every picker.json in my designated picker folder when dwpicker.show() was called.  So I deleted all of my picker.json files except for the one that I wanted, but it seems to be cached somewhere and still opens the deleted files (without the images).

Maya error of : Cannot delete "pickername_dwpicker_data' as it has locked or read-only children." for all the deleted .json pickers

**Comment by luckylyk** [comment]
Hi Kersey, 
Sorry for the delay !
What you described is the normal default picker behavior.
When you open a picker, it is imported inside the Maya scene. This is requested by many animators to keep the AnimSchool behavior which allow team to make some edit shot by shot.
However it is possible to force the picker to open itself without loading the local storing data:
dwpicker.show(ignore_scene_pickers=True)

It is also possible to lock the pickers to avoid the picker storing data locally:
dwpicker.show(editable=False)

And finally you can specify what pickers you would like to open with the UI:
dwpicker.show(pickers=['path to picker1', 'path to picker2'])

And all those options can be combined.
I know that some studio coded some custom dwpicker startup based on the shot context and the shot casting.


About the Maya error you mentionned, the data nodes are not locked by the tool. But it is possible that you can delete it because it is holded by a reference (inside the rig for instance) ?


Have a nice day
Lionel
