### ISSUE TITLE
Ability to lock the view pan and zoom of the viewed picker

### ISSUE THREAD

**Issue by alfsici** [DreamWall-Animation/dwpicker#8]
This option would come in handy, for some of the pickers, when there are a lot of buttons that are scripts(to open tools not picking things), it would come handy to simply be able to lock the pan and zoom option of a UI so that when the main UI is resized, the entire button layout would simply resize accordingly to the main window, but always displaying all the buttons.
This way the user could make the picker ui very small and still have the ability to see and use the buttons, without loosing them around by accidentally middle mouse drag/roll, or F to focus.

**Comment by luckylyk** [comment]
Lock the pan and zoom as a gobal setting or a picker setting ?

**Comment by alfsici** [comment]
To further explain , i see these type of scenarios for my team: 
A :  selection-picker (current behavior)
B :  "animation tools" picker ui's, which has a bunch of buttons that runs tools only , similar to what a shelf would provide, 
DreamWall picker tho would remove the need for the shelf altogether and make things more organized.

For the B type of pickers, i would set the zoom lock On, from the advance editor, so that the ui will always display the full extent of the available buttons, which visually are locked to the main ui size.
If the user wants to see the buttons bigger, it would make the main ui window bigger, although, even in situations where the screen space is limited, or the window is made smaller or has an odd shape (for instance by docking it in the maya UI) or to accomodate one of the other selection-pickers that are opened, when clicking on a B type picker, this will always display all the buttons, eliminating the need for navigating the view to run a tool.
(the button might look smaller/bigger given window size)

**Comment by luckylyk** [comment]
Ok understood,
This is not exactly the purpose of the Dreamwall Picker. So I will not implement this.

By the way, the dwpicker is based on another tool i wrote: Hotbox designer. The editor is the same but it is design to make hotboxes menus. That tool provide small api to create static widget instead of hotbox. I recommand you to use it. There is example on documentation to make a widget.

If you would like to have something less around code, you can post this request on that tool, I'm up to implement good ideas there as well.

https://github.com/luckylyk/hotbox_designer

**Comment by luckylyk** [comment]
Well after reflection, it is not too much work to do for dwpicker either. Then I keep the ticket opened as low prio.
