### ISSUE TITLE
script action wont set attributes when the rig is referenced

### ISSUE THREAD

**Issue by adevra** [DreamWall-Animation/dwpicker#98]
I was experimenting with picker and wanted to have a reset pose button that triggers for example:
```
// Transform Data for "FKThumbFinger1_L":
setAttr "FKThumbFinger1_L.tx" 0;
setAttr "FKThumbFinger1_L.ty" 0;
setAttr "FKThumbFinger1_L.tz" 0;
setAttr "FKThumbFinger1_L.rx" 0;
setAttr "FKThumbFinger1_L.ry" 0;
setAttr "FKThumbFinger1_L.rz" 0;
setAttr "FKThumbFinger1_L.sx" 1;
setAttr "FKThumbFinger1_L.sy" 1;
setAttr "FKThumbFinger1_L.sz" 1;

```
couldn't make it work with referenced rigs,
tried doing with setting those controllers as targets as well but no luck,
any ideas?

**Comment by luckylyk** [comment]
Hi adevra,
This is indeed not working because using your rig in reference automatically add a namespace to your scene.
You should change youre script and rely on the picker namespace to dynamically build the names of your attribute to set.
I'm too lasy to write something on mel language but here is an example of what you can do in python:

```python
import dwpicker
from maya import cmds
cmds.setAttr(f'{dwpicker.current_namespace()}:FKThumbFinger1_L.tx', 0)
```

Note that I just exposed the dwpicker.current_namespace() in the API, then you need to take the latest version of the code to ensure it works

Cheers
Lio
